# docker-compose up -d --build
# based on https://medium.com/@lojorider/docker-with-cgi-perl-a4558ab6a329
# docker exec -it  homepage_web bash

version: '3.4'
services:
    web:
        container_name: homepage_web
        build:
            context: .
            network: default
        restart: always
        volumes:
            - ./weblog:/var/log/nginx/web
        ports:
            - "8084:80"

networks:
   default:
       external:
          name: RichiNet
